# Generated by Django 5.0.8 on 2024-08-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publicationtwo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicationTwo',
        ),
    ]
