# Generated by Django 5.0.8 on 2024-08-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_hashtag_alter_category_options_publication_hashtags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='is_sugar',
            new_name='is_active',
        ),
    ]
