# Generated by Django 5.0.8 on 2024-08-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_publicationcomment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationcomment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
