# Generated by Django 5.0.8 on 2024-08-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_contactclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_ky',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_ru',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
